[package]
name = "locksmith"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["json"] }
directories = "4.0.1"
rand = "0.8.5"
serde_json = "1.0.89"
